server:
  port: 8082

spring:
  application:
    name: audit-service

  datasource:
    url: jdbc:postgresql://localhost:5433/trading
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: audit-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "com.demo.commons.model.kafka,com.demo.trade_portfolio.model.kafka"
        spring.json.value.default.type: com.demo.commons.model.kafka.TradeEvent
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

app:
  kafka:
    topics:
      trades-raw: trades.raw.topic
      audit-dlq: audit.dlq.topic

logging:
  level:
    com.demo.audit: INFO
  file:
    name: /tmp/audit-service.log
