server:
  port: 8087

spring:
  application:
    name: portfolio-service

  data:
    redis:
      host: localhost
      port: 6380

  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: portfolio-cache-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.demo.commons.model.kafka"

jwt:
  secret: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
  expiration-ms: 86400000

app:
  execution-service:
    base-url: http://localhost:8086
  kafka:
    topics:
      trades-processed: trades.processed.topic
      prices-updated: prices.updated.topic
      portfolio-dlq: portfolio.dlq.topic

logging:
  level:
    com.demo.portfolio: INFO
  file:
    name: /tmp/portfolio-service.log
